version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
  
  testa:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "TestA is done"
      - run: sleep 5
  testb:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "TestB is done"
      - run: sleep 5
  
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A final goodbye"
      - run: sleep5


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testa:
      # only run this job if build1 succeeds
          requires:
            - build
      - testb:
          requires:
            - build
      - deploy:
          requires:
          - testa
          - testb
          