version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
  
  testa:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "TestA is done"
      - run: sleep 5
  testb:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "TestB is done"
      - run: sleep 5
  commands:
    sayhello:
      description: "A very simple command for demonstration purposes"
      parameters:
        to:
          type: string
          default: "Hello World"
    steps:
      - run: echo << parameters.to >>
  
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A final goodbye test done"
      - run: sleep 5


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testa:
      # only run this job if build1 succeeds
          requires:
            - build
      - testb:
          requires:
            - build
      - commands:
          requires:
            - build
      - deploy:
          requires:
            - testa
            - testb
            - commands
          