version: 2
jobs:
  build1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
  build2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hello"
      - run: sleep 5
workflows:
  version: 2
  build1_and_build2:
    jobs:
      - build1
      - build2:
      # only run this job if build1 succeeds
          requires:
            - build